---
services:
  reference_sheets:
    container_name: reference_sheets
    image: reference_sheets:latest
    build:
      context: .
      dockerfile: ./reference_sheets/Dockerfile
      args:
        - LILY_VERSION=$LILY_VERSION
        - APP_PATH=$APP_PATH
    entrypoint:
      - python3
      - ${APP_PATH}/main.py
    env_file:
      - ./reference_sheets/.env
    volumes:
      - ./$APP_PATH/:/$APP_PATH/:rw
    command:
      - --debug
