---
version: "3.9"

services:
  music_theory:
    container_name: music_theory
    image: music_theory:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - LILLY_VERSION=$LILLY_VERSION
    env_file:
      - .env
    volumes:
      - ./reference/:/reference/:z
    command: tail -F foo
